services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: easyrice
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: easyrice_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    platform: linux/amd64
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./Backend
    ports:
      - "3000:3000"
    volumes:
      - ./Backend:/app
      - /app/node_modules
    platform: linux/amd64
    depends_on:
      - database
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_URL=postgresql://easyrice:password123@database:5432/easyrice_db?schema=public

volumes:
  pgdata:
